### ISSUE TITLE
We're interested in this!!

### ISSUE THREAD

**Issue by mjdavies** [rishabhp/sso-rails-provider#1]
Hello there

We'd very much like to give this a spin.

Are there any docs on how to use it?

**Comment by rishabhp** [comment]
No docs, should work as it is. Although I did a little writeup on the internals of it that you can find here - http://codetheory.in/rails-devise-omniauth-sso/

**Comment by mjdavies** [comment]
Thanks riashaphp, I'll have a look.

Would you be interested in me putting together a docker build for the app?

Unless you have on already?

**Comment by mjdavies** [comment]
Hi

I've just tried to start the app and running into some problems.

rake db:migrate is failing

rake aborted!
NameError: uninitialized constant FB_APP_ID
/vagrant/config/initializers/devise.rb:263:in `block in <top (required)>'
/vagrant/config/initializers/devise.rb:3:in `<top (required)>'
/vagrant/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

Any ideas how to get around this?

**Comment by mjdavies** [comment]
My Bad

I just commented out the omniauth config block that comes in the app and it was fine.

  config.omniauth :facebook, FB_APP_ID, FB_APP_SECRET,
                  scope: 'email', info_fields: 'name, email'

**Comment by jpmckinney** [comment]
See also #3

**Comment by cobolserverpages** [comment]
Here are some notes I took as a total newbie to get the client and provider apps to work for me. 

1) Before attempting to get it to run, create your facebook developer account and app (https://developers.facebook.com/docs/apps/register#developer-account). This will give you the values to use in place for FP_APP_ID and FP_APP_SECRET in the sample apps. If you don't do this you'll get an error from facebook when you visit the sign-up/sign-in with facebook links.

2) If you're running the sample apps locally, facebook will give you an error due to the redirect back to your server containing localhost. I was able to get around this by choosing 'www' as the platform for my app in the facebook developer portal and then adding 'http://localhost:3000' as the site-url of my app. 

3) I missed the step of registering the client sample app on the provider sample app. This can done as follows:

cd [somewhere]/sso-rails-provider
rails console
> c = Client.create :id => 1, :name => "App 1", :app_id => "key", :app_secret => "secret"

After taking these actions, the sample apps seem to work as intended for me.

I'm very grateful to @rishabhp for sharing this code.

**Comment by rishabhp** [comment]
@cobolserverpages Would you consider posting this information as a comment [on the article](http://codetheory.in/rails-devise-omniauth-sso/) too ? That'd be really helpful for other people too!

**Comment by cobolserverpages** [comment]
@rishabhp Sure, makes sense. I've posted it in the article as well.

**Comment by samuelpares** [comment]
Guys, someone still has the article? I'm struggling here to set it up.

**Comment by mjdavies** [comment]
https://web.archive.org/web/20180204125500/http://codetheory.in/rails-devise-omniauth-sso/

Way Back Machine to the rescue again!!
